MERCEDES DATA SET 
ONE HOT ENCODING TECHNIQUE

In [8]:
import pandas as pd
import numpy as np

In [14]:
df= pd.read_csv("Mercedes data.csv",usecols=['X1','X2','X3','X4','X5','X6'])

In [15]:
df.head(5)

  X1  X2 X3 X4 X5 X6
0  v  at  a  d  u  j
1  t  av  e  d  y  l
2  w   n  c  d  x  j
3  t   n  f  d  x  l
4  v   n  f  d  h  d

#Let's find the unique values present in each category

In [19]:
for col in df.columns:
    print(col,':',len(df[col].unique()),'labels')

X1 : 27 labels
X2 : 44 labels
X3 : 7 labels
X4 : 4 labels
X5 : 29 labels
X6 : 12 labels

In [20]:
#As we can see there are 27 unique labels in X1 and similarly in other categories.

In [23]:
pd.get_dummies(df,drop_first=True).shape

(4209, 117)

In [24]:
#As we can see a large number of columns are formed which can lead to curse of Dimentionallity
#So we will perform another meathod

In [35]:
total= df['X2'].value_counts().sort_values(ascending=False).head(10)

In [36]:
top_10 = [x for x in total.index]

In [52]:
top_10
#Now we will perform One Hot Encoding to the first ten labels only

['as', 'ae', 'ai', 'm', 'ak', 'r', 'n', 's', 'f', 'e']

In [59]:
for label in top_10:
    df[label]= np.where(df['X2']==label,1,0)
df[['X2']+top_10].head(40)

    X2  as  ae  ai  m  ak  r  n  s  f  e
0   at   0   0   0  0   0  0  0  0  0  0
1   av   0   0   0  0   0  0  0  0  0  0
2    n   0   0   0  0   0  0  1  0  0  0
3    n   0   0   0  0   0  0  1  0  0  0
4    n   0   0   0  0   0  0  1  0  0  0
5    e   0   0   0  0   0  0  0  0  0  1
6    e   0   0   0  0   0  0  0  0  0  1
7   as   1   0   0  0   0  0  0  0  0  0
8   as   1   0   0  0   0  0  0  0  0  0
9   aq   0   0   0  0   0  0  0  0  0  0
10   r   0   0   0  0   0  1  0  0  0  0
11   e   0   0   0  0   0  0  0  0  0  1
12  ai   0   0   1  0   0  0  0  0  0  0
13   e   0   0   0  0   0  0  0  0  0  1
14  as   1   0   0  0   0  0  0  0  0  0
15  ak   0   0   0  0   1  0  0  0  0  0
16   e   0   0   0  0   0  0  0  0  0  1
17  as   1   0   0  0   0  0  0  0  0  0
18   m   0   0   0  1   0  0  0  0  0  0
19  ak   0   0   0  0   1  0  0  0  0  0
20   m   0   0   0  1   0  0  0  0  0  0
21  as   1   0   0  0   0  0  0  0  0  0
22   a   0   0   0  0   0  0  0  0  0  0
23   m   0   0   0  1   0  0  0  0  0  0
24  ak   0   0   0  0   1  0  0  0  0  0
25   m   0   0   0  1   0  0  0  0  0  0
26  as   1   0   0  0   0  0  0  0  0  0
27  as   1   0   0  0   0  0  0  0  0  0
28  as   1   0   0  0   0  0  0  0  0  0
29   m   0   0   0  1   0  0  0  0  0  0
30  as   1   0   0  0   0  0  0  0  0  0
31  as   1   0   0  0   0  0  0  0  0  0
32   m   0   0   0  1   0  0  0  0  0  0
33  as   1   0   0  0   0  0  0  0  0  0
34  as   1   0   0  0   0  0  0  0  0  0
35  ai   0   0   1  0   0  0  0  0  0  0
36  as   1   0   0  0   0  0  0  0  0  0
37   k   0   0   0  0   0  0  0  0  0  0
38  as   1   0   0  0   0  0  0  0  0  0
39  as   1   0   0  0   0  0  0  0  0  0

In [64]:
def getting_dummy(data,variable,top_xlabels) :
    for label in top_xlabels:
        data[variable+'_'+label]= np.where(df[variable]==label,1,0)

In [65]:
getting_dummy(df,'X2',top_10)

In [70]:
df= pd.read_csv("Mercedes data.csv",usecols=['X1','X2','X3','X4','X5','X6'])

In [71]:
getting_dummy(df,'X2',top_10)

In [72]:
df.head()

,X1,X2,X3,X4,X5,X6,X2_as,X2_ae,X2_ai,X2_m,X2_ak,X2_r,X2_n,X2_s,X2_f,X2_e
0,v,at,a,d,u,j,0,0,0,0,0,0,0,0,0,0
1,t,av,e,d,y,l,0,0,0,0,0,0,0,0,0,0
2,w,n,c,d,x,j,0,0,0,0,0,0,1,0,0,0
3,t,n,f,d,x,l,0,0,0,0,0,0,1,0,0,0
4,v,n,f,d,h,d,0,0,0,0,0,0,1,0,0,0

In [73]:
total= df['X1'].value_counts().sort_values(ascending=False).head(10)

In [74]:
top_10 = [x for x in total.index]

In [75]:
getting_dummy(df,'X1',top_10)
df.head(10)

,X1,X2,X3,X4,X5,X6,X2_as,X2_ae,X2_ai,X2_m,...,X1_aa,X1_s,X1_b,X1_l,X1_v,X1_r,X1_i,X1_a,X1_c,X1_o
0,v,at,a,d,u,j,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1,t,av,e,d,y,l,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,w,n,c,d,x,j,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,t,n,f,d,x,l,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,v,n,f,d,h,d,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
5,b,e,c,d,g,h,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
6,r,e,f,d,f,h,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
7,l,as,f,d,f,j,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0
8,s,as,e,d,f,i,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0
9,b,aq,c,d,f,a,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0

In [76]:
total= df['X3'].value_counts().sort_values(ascending=False).head(10)
top_10 = [x for x in total.index]

In [77]:
getting_dummy(df,'X3',top_10)
df.head(10)

,X1,X2,X3,X4,X5,X6,X2_as,X2_ae,X2_ai,X2_m,...,X1_a,X1_c,X1_o,X3_c,X3_f,X3_a,X3_d,X3_g,X3_e,X3_b
0,v,at,a,d,u,j,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1,t,av,e,d,y,l,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,w,n,c,d,x,j,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
3,t,n,f,d,x,l,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
4,v,n,f,d,h,d,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
5,b,e,c,d,g,h,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
6,r,e,f,d,f,h,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
7,l,as,f,d,f,j,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
8,s,as,e,d,f,i,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
9,b,aq,c,d,f,a,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [78]:
total= df['X4'].value_counts().sort_values(ascending=False).head(10)
top_10 = [x for x in total.index]
getting_dummy(df,'X4',top_10)
df.head(10)

,X1,X2,X3,X4,X5,X6,X2_as,X2_ae,X2_ai,X2_m,...,X3_f,X3_a,X3_d,X3_g,X3_e,X3_b,X4_d,X4_a,X4_b,X4_c
0,v,at,a,d,u,j,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
1,t,av,e,d,y,l,0,0,0,0,...,0,0,0,0,1,0,1,0,0,0
2,w,n,c,d,x,j,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3,t,n,f,d,x,l,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
4,v,n,f,d,h,d,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
5,b,e,c,d,g,h,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
6,r,e,f,d,f,h,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
7,l,as,f,d,f,j,1,0,0,0,...,1,0,0,0,0,0,1,0,0,0
8,s,as,e,d,f,i,1,0,0,0,...,0,0,0,0,1,0,1,0,0,0
9,b,aq,c,d,f,a,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [79]:
total= df['X5'].value_counts().sort_values(ascending=False).head(10)
top_10 = [x for x in total.index]
getting_dummy(df,'X5',top_10)
df.head(10)

,X1,X2,X3,X4,X5,X6,X2_as,X2_ae,X2_ai,X2_m,...,X5_v,X5_w,X5_q,X5_r,X5_d,X5_s,X5_n,X5_p,X5_m,X5_i
0,v,at,a,d,u,j,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,t,av,e,d,y,l,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,w,n,c,d,x,j,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,t,n,f,d,x,l,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,v,n,f,d,h,d,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,b,e,c,d,g,h,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,r,e,f,d,f,h,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,l,as,f,d,f,j,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,s,as,e,d,f,i,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,b,aq,c,d,f,a,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [80]:
total= df['X6'].value_counts().sort_values(ascending=False).head(10)
top_10 = [x for x in total.index]
getting_dummy(df,'X6',top_10)
df.head(10)

,X1,X2,X3,X4,X5,X6,X2_as,X2_ae,X2_ai,X2_m,...,X6_g,X6_j,X6_d,X6_i,X6_l,X6_a,X6_h,X6_k,X6_c,X6_b
0,v,at,a,d,u,j,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,t,av,e,d,y,l,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2,w,n,c,d,x,j,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,t,n,f,d,x,l,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
4,v,n,f,d,h,d,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
5,b,e,c,d,g,h,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
6,r,e,f,d,f,h,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
7,l,as,f,d,f,j,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0
8,s,as,e,d,f,i,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0
9,b,aq,c,d,f,a,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [86]:
df.drop(['X1','X2','X3','X4','X5','X6'],axis='columns', inplace=True)

In [87]:
df.head(10)

,X2_as,X2_ae,X2_ai,X2_m,X2_ak,X2_r,X2_n,X2_s,X2_f,X2_e,...,X6_g,X6_j,X6_d,X6_i,X6_l,X6_a,X6_h,X6_k,X6_c,X6_b
0,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2,0,0,0,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
4,0,0,0,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
6,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
7,1,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
8,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0

Here we have perfectly encoded data set done by One Hot Encoding for multiple varialbles.